<?php

namespace Setting\Bundle\ToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GlobalOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalOptionRepository extends EntityRepository
{
}
