<?php

namespace Setting\Bundle\ToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SyndicateModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyndicateModuleRepository extends EntityRepository
{
}
