<?php

namespace Setting\Bundle\ToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SyndicateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyndicateRepository extends EntityRepository
{

    public function insertSyndicateMenu($entityName,$id){

        $em = $this->_em;

        if($id){

            $reEntity = $em->getRepository($entityName)->find($id);

            $menuUser = $reEntity->getUser()->getId();

            $menus = $reEntity->getInstituteType();

            foreach ($menus as $menu){

                $sid = $menu->getId();
                $syEntity = $em->getRepository('SettingToolBundle:Syndicate')->find($sid);

                $menu = $syEntity -> getName();
                $menuSlug = $syEntity -> getSlug();
                $menuUniqueCode = $syEntity -> getUniqueCode();

                $entity = new Menu();

                $entity->setMenu($menu);
                $entity->setMenuSlug($menuSlug);
                $entity->setUser($menuUser);
                $entity->setUniqueCode($menuUniqueCode);
                $em->persist($entity);

            }

            $em->flush();



        }


    }

    public  function updateSyndicateMenu($id)
    {
        $em = $this->_em;

        if($id){

            $reEntity = $em->getRepository('SettingToolBundle:Syndicate')->find($id);

            $menu = $reEntity->getMenu();
            $menuSlug = $reEntity->getMenuSlug();
            $menuUser = $reEntity->getUser()->getId();
            $menuUniqueCode = $reEntity->getUniqueCode();

            $entity = $em->getRepository('SettingContentBundle:Menu')->findOneBy(array('uniqueCode' => $menuUniqueCode));

            if(!empty($entity)){

                $entity->setMenu($menu);
                $entity->setMenuSlug($menuSlug);
                $entity->setUser($menuUser);

                $em->persist($entity);
                $em->flush();
            }

        }

    }


}
