homepage:
    pattern: /
    defaults: { _controller: UserBundle:Default:index }

user_deactive:
    pattern: /user/deactive/{id}
    defaults: { _controller: UserBundle:User:userDeactive }
    requirements:
          id: \d+

user_active:
    pattern: /user/active/{id}
    defaults: { _controller: UserBundle:User:userActive }
    requirements:
          id: \d+

username_check:
    pattern: /username/check
    defaults: { _controller: UserBundle:User:usernameCheck }
    options:
            expose: true

requisition_graph_Data:
    pattern: /requisition/graph
    defaults: { _controller: UserBundle:Default:getRequisitionGraph }
    options:
            expose: true

Purchase_order_graph_Data:
    pattern: /Purchase/graph
    defaults: { _controller: UserBundle:Default:getPurchaseGraph }
    options:
            expose: true

email_check:
    pattern: /email/check
    defaults: { _controller: UserBundle:User:emailCheck }
    options:
            expose: true

fos_user_security:
     resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
     resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
     prefix: /profile


fos_user_resetting:
     resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
     prefix: /resetting

fos_user_change_password:
     resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
     prefix: /profile

Core_user_group:
    resource: "@UserBundle/Resources/config/user/user-manage.yml"
    prefix: /users

register:
    pattern: /register
    defaults: { _controller: UserBundle:ManageUser:create}
