parameters:
#    web_setting.example.class: Web\Bundle\SettingBundle\Example

services:
#    web_setting.example:
#        class: %web_setting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
