<?php

namespace Setting\Bundle\AppearanceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{


    public function updateMenu($data)
    {

        $em = $this->_em;
        $i=0;
        foreach ($data['id'] as $key ){
            $menu = ($data['menu'][$i]) ? $data['menu'][$i] : Null ;
            $entity = $em->getRepository('SettingAppearanceBundle:Menu')->findOneBy(array('id'=>$key));
            if (!empty($entity)) {
                $entity->setMenu($menu);
                $em->persist($entity);
            }
            $i++;
        }
        $em->flush();


    }

    public function removeSiteSettingMenu($reEntity){

        $em =$this->_em;

        $em = $this->_em;

        $modules = $reEntity->getModules();
        $id = $reEntity->getId();
        $checkEntity = $em->getRepository('SettingAppearanceBundle:Menu')->findBy(array('user'=>17,'siteSetting'=>5));
        foreach($checkEntity as $module ){

            if($module->getSyndicate()){
               echo $module->getSyndicate()->getId();
            }

        }

        exit;

    }

}
