<?php

namespace Setting\Bundle\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassRoutineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassRoutineRepository extends EntityRepository
{
}
