<?php

namespace Setting\Bundle\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Setting\Bundle\AppearanceBundle\Entity\Menu;

/**
 * ContactPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactPageRepository extends EntityRepository
{
    public function globalOptionContact($user)
    {
        $em = $this->_em;

        $reEntity = $em->getRepository('SettingContentBundle:ContactPage')->findOneBy(array('user'=>$user));
        if(empty($reEntity) && $user){

            $entity = New ContactPage();
            $entity->setUser($user);
            $entity->setName("Contact us");
            $em->persist($entity);

            $entity = New Menu();
            $entity->setMenu('Contact us');
            $entity->setMenuSlug('contact-us');
            $entity->setUser($user);
            $entity->setDefaultMenu(true);
            $em->persist($entity);

            $em->flush();
        }


    }

}
