<?php

namespace Setting\Bundle\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactMessageRepository extends EntityRepository
{
    public function insertMessage($data)
    {

        $em = $this->_em;
        $user = $em->getRepository('UserBundle:User')->find($data['user']);

        if($data){
            $entity = new ContactMessage();
            $entity->setUser($user);
            $entity->setName($data['name']);
            $entity->setEmail($data['email']);
            $entity->setContent($data['content']);
            $em->persist($entity);
            $em->flush();
        }

    }
}
