<?php

namespace Setting\Bundle\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HomeBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeBlockRepository extends EntityRepository
{

    public function getMenuLists($user){


        $em =$this->_em;
        $entity = $em->getRepository('SettingAppearanceBundle:Menu')->findBy(array('user'=>$user,'status'=>1),array('menu'=>'asc'));
        if($entity){
            return $entity;
        }else{
            return false;
        }



    }

    public function insertHomeBlock($data,$homePage)
    {

        $em =$this->_em;
        $i=0;
        if(!empty($data['blockName'])){
            foreach($data['blockName'] as $block ){

                $menuId = $data['menu'][$i];
                $menu = $em->getRepository('SettingAppearanceBundle:Menu')->findOneBy(array('id'=>$menuId));

                /*if($data['blockId'][$i] > 0 ){

                    $id= $data['blockId'][$i];
                    $entity = $em->getRepository('SettingContentBundle:HomeBlock')->findOneBy(array('id'=>$id));
                    $entity->setHomePage($homePage);
                    $entity->setName($block);
                    $entity->setMenu($menu);
                    $entity->setContent($data['content'][$i]);
                    $em->persist($entity);

                }else{*/

                    $entity = new HomeBlock();
                    $entity->setHomePage($homePage);
                    $entity->setName($block);
                    $entity->setMenu($menu);
                    $entity->setContent($data['content'][$i]);
                    $em->persist($entity);
                //}
                $i++;
            }
            $em->flush();
            if(!empty($data['removeId'])){
                $this->removeBlock($data['removeId']);
            }

        }

    }

    private  function removeBlock($data)
    {

        $em =$this->_em;
        foreach($data as $block ){
            $entity = $em->getRepository('SettingContentBundle:HomeBlock')->findOneBy(array('id'=>$block));
            $em->remove($entity);
        }
        $em->flush();

    }
}
