<?php

namespace Setting\Bundle\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Setting\Bundle\AppearanceBundle\Entity\Menu;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{

    public  function insertPageMenu($id)
    {

        $entity = new Menu();
        $em = $this->_em;
        if($id){

            $reEntity = $em->getRepository('SettingContentBundle:Page')->find($id);

            $menu = $reEntity->getMenu();
            $menuSlug = $reEntity->getMenuSlug();
            $menuUser = $reEntity->getUser();

            $entity->setMenu($menu);
            $entity->setMenuSlug($menuSlug);
            $entity->setUser($menuUser);
            $entity->setPage($reEntity);

            $em->persist($entity);
            $em->flush();
        }

    }
    public  function updatePageMenu($id)
    {

        $em = $this->_em;
        if($id){

            $reEntity = $em->getRepository('SettingContentBundle:Page')->find($id);

            $menu = $reEntity->getMenu();
            $menuSlug = $reEntity->getMenuSlug();
            $menuUser = $reEntity->getUser();

            $entity = $em->getRepository('SettingAppearanceBundle:Menu')->findOneBy(array('page' => $id));
            if(!empty($entity)){

                $entity->setMenu($menu);
                $entity->setMenuSlug($menuSlug);
                $em->persist($entity);
                $em->flush();

            }else{

                $this->insertPageMenu($id);
            }
        }

    }

}
