<?php

namespace Setting\Bundle\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SyndicateContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyndicateContentRepository extends EntityRepository
{

    public function insertContent($id)
    {
        $em = $this->_em;
        $reEntity = $em->getRepository('SettingToolBundle:Syndicate')->find($id);

        if($reEntity){
            $entity = new SyndicateContent();
            $entity->setSyndicate($reEntity);
            $entity->setName($reEntity->getName());
            $entity->setStatus(true);
            $em->persist($entity);
            $em->flush();
        }


    }

}
