parameters:
#    setting_tool.example.class: Setting\Bundle\ToolBundle\Example

services:
#    setting_tool.example:
#        class: %setting_tool.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
