<?php

namespace Mobile\SettingsBundle\Service;

use Doctrine\ORM\EntityManager;
use Doctrine\Bundle\DoctrineBundle\Registry;
use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\Connection;
use Setting\Bundle\AppearanceBundle\Entity\Menu;
use Symfony\Component\Debug\Debug;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * RequestManager
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class MenuTreeManager

{

    /**
     * @var EntityManager
     */
    protected  $em;
    /**
     * @var \Doctrine\Bundle\DoctrineBundle\Registry
     */
    private $doctrine;

    public function  __construct(Registry $doctrine)
    {
        $this->doctrine = $doctrine;
        $this->em = $doctrine->getManager();
    }

    public function checkModule($slug)
    {
        $em = $this->em;

        $module = $em->getRepository('SettingToolBundle:Module')->findOneBy(array('menuSlug'=>$slug));
        $syndicateModule = $em->getRepository('SettingToolBundle:SyndicateModule')->findOneBy(array('menuSlug'=>$slug));


    }

    public function getMenuTree($arr,$subdomain)
    {

       // $subdomain ='mobile/'.$subdomainName;

        $value ='';
        $value .='<ul>';
        foreach ($arr as $val) {

            if (!empty($val->getMenu()->getMenu())) {
                $subIcon = (count($val->getChildren()) > 0 ) ? 1 : 2 ;
                if($subIcon == 1){
                    $value .= '<li><a href="/mobile/'.$subdomain.'/'.$val->getMenu()->getMenuSlug().'">' . $val->getMenu()->getMenu().'</a>';
                    $value .= $this->getMenuTree($val->getChildren(),$subdomain);
                }else{
                    $value .= '<li><a href="/mobile/'.$subdomain.'/'.$val->getMenu()->getMenuSlug().'">' . $val->getMenu()->getMenu().'</a>';
                }

                $value .= '</li>';
            } else {
                $value .= '<li><a href="/mobile/'.$subdomain.'/'.$val->getMenu()->getMenuSlug().'">'.$val->getMenu()->getMenu() . '</a></li>';
            }
        }
        $value .='</ul>';

        return $value;

    }

    public function getModuleTheme($menu)
    {


        /* this condition return module,syndicate module , page ,syndicate functional theme return. */
        $moduleTheme = false;

        if($menu->getModule()){
            $moduleTheme = $menu->getModule()->getModuleClass();
        }elseif($menu->getSyndicateModule()){
            $moduleTheme = $menu->getSyndicateModule()->getModuleClass();
        }elseif($menu->getSyndicate()){
            $moduleTheme = 'SyndicateContent';
        }

        return $moduleTheme;


    }


}
