<?php

namespace Core\UserBundle\Permission\Provider;

/**
 * Security Provider
 *
 * @author Mohammad Emran Hasan <phpfour@gmail.com>
 */
class SecurityPermissionProvider implements ProviderInterface
{
    public function getPermissions()
    {
        return array(
            'ROLE_AREA_USERS'                 => array('ROLE_AREA_VIEW', 'ROLE_AREA_ADD', 'ROLE_AREA_UPDATE', 'ROLE_AREA_DELETE', 'ROLE_AREA_RESTORE'),
            'ROLE_CATEGORY_USERS'             => array('ROLE_CATEGORY_VIEW', 'ROLE_CATEGORY_ADD', 'ROLE_CATEGORY_UPDATE', 'ROLE_CATEGORY_DELETE', 'ROLE_CATEGORY_RESTORE'),
            'ROLE_COST_HEADER_USERS'          => array('ROLE_COST_HEADER_VIEW', 'ROLE_COST_HEADER_ADD', 'ROLE_COST_HEADER_UPDATE', 'ROLE_COST_HEADER_DELETE', 'ROLE_COST_HEADER_RESTORE'),
            'ROLE_ITEM_USERS'                 => array('ROLE_ITEM_VIEW', 'ROLE_ITEM_ADD', 'ROLE_ITEM_UPDATE', 'ROLE_ITEM_DELETE', 'ROLE_ITEM_RESTORE'),
            'ROLE_ITEM_TYPE_USERS'            => array('ROLE_ITEM_TYPE_VIEW', 'ROLE_ITEM_TYPE_ADD', 'ROLE_ITEM_TYPE_UPDATE', 'ROLE_ITEM_TYPE_DELETE', 'ROLE_ITEM_TYPE_RESTORE'),
            'ROLE_PROJECT_USERS'              => array('ROLE_PROJECT_VIEW', 'ROLE_PROJECT_ADD', 'ROLE_PROJECT_UPDATE', 'ROLE_PROJECT_DELETE', 'ROLE_PROJECT_RESTORE'),
            'ROLE_PROJECT_TYPE_USERS'         => array('ROLE_PROJECT_TYPE_VIEW', 'ROLE_PROJECT_TYPE_ADD', 'ROLE_PROJECT_TYPE_UPDATE', 'ROLE_PROJECT_TYPE_DELETE', 'ROLE_PROJECT_TYPE_RESTORE'),
            'ROLE_SUB_CATEGORY_USERS'         => array('ROLE_SUB_CATEGORY_VIEW', 'ROLE_SUB_CATEGORY_ADD', 'ROLE_SUB_CATEGORY_UPDATE', 'ROLE_SUB_CATEGORY_DELETE', 'ROLE_SUB_CATEGORY_RESTORE'),
            'ROLE_TERMS_AND_CONDITIONS_USERS' => array('ROLE_TERMS_AND_CONDITIONS_VIEW', 'ROLE_TERMS_AND_CONDITIONS_ADD', 'ROLE_TERMS_AND_CONDITIONS_UPDATE', 'ROLE_TERMS_AND_CONDITIONS_DELETE', 'ROLE_TERMS_AND_CONDITIONS_RESTORE'),
            'ROLE_VENDOR_USERS'               => array('ROLE_VENDOR_VIEW', 'ROLE_VENDOR_ADD', 'ROLE_VENDOR_UPDATE', 'ROLE_VENDOR_DELETE', 'ROLE_VENDOR_RESTORE'),

            'ROLE_RECEIVE_USERS'              => array('ROLE_RECEIVE_VIEW', 'ROLE_RECEIVE_ADD', 'ROLE_RECEIVE_UPDATE', 'ROLE_RECEIVE_DELETE', 'ROLE_RECEIVE_RESTORE', 'ROLE_RECEIVE_DELIVERY'),
            'ROLE_REPORT_USERS'               => array('ROLE_REPORT_VIEW', 'ROLE_REPORT_ADD', 'ROLE_REPORT_UPDATE', 'ROLE_REPORT_DELETE', 'ROLE_REPORT_RESTORE'),
            'ROLE_BUDGET_USERS'               => array('ROLE_BUDGET_VIEW', 'ROLE_BUDGET_ADD', 'ROLE_BUDGET_UPDATE', 'ROLE_BUDGET_DELETE', 'ROLE_BUDGET_RESTORE'),
            'ROLE_DOCUMENT_USERS'             => array('ROLE_DOCUMENT_VIEW', 'ROLE_DOCUMENT_ADD', 'ROLE_DOCUMENT_UPDATE', 'ROLE_DOCUMENT_DELETE', 'ROLE_DOCUMENT_RESTORE'),
            'ROLE_PURCHASE_ORDER_USERS'       => array('ROLE_PURCHASE_ORDER_VIEW', 'ROLE_PURCHASE_ORDER_ADD', 'ROLE_PURCHASE_ORDER_UPDATE', 'ROLE_PURCHASE_ORDER_DELETE', 'ROLE_PURCHASE_ORDER_SUSPEND'),
            'ROLE_PURCHASE_REQUISITION_USERS' => array('ROLE_PURCHASE_REQUISITION_CLOSE', 'ROLE_PURCHASE_REQUISITION_APPROVE', 'ROLE_PURCHASE_REQUISITION_CLAIM', 'ROLE_PURCHASE_REQUISITION_VIEW', 'ROLE_PURCHASE_REQUISITION_ADD', 'ROLE_PURCHASE_REQUISITION_UPDATE', 'ROLE_PURCHASE_REQUISITION_DELETE', 'ROLE_PURCHASE_REQUISITION_SUSPEND'),

            'ROLE_PURCHASE_ORDER_APPROVE_USERS'       => array('ROLE_PURCHASE_ORDER_APPROVE_ONE', 'ROLE_PURCHASE_ORDER_APPROVE_TWO', 'ROLE_PURCHASE_ORDER_APPROVE_THREE', 'ROLE_PURCHASE_ORDER_VIEW', 'ROLE_PURCHASE_ORDER_ADD', 'ROLE_PURCHASE_ORDER_UPDATE', 'ROLE_PURCHASE_ORDER_DELETE', 'ROLE_PURCHASE_ORDER_SUSPEND'),

            'ROLE_MANAGE_USERS'      => array('ROLE_MANAGE_USERS_VIEW', 'ROLE_MANAGE_ADD', 'ROLE_MANAGE_UPDATE', 'ROLE_MANAGE_DELETE', 'ROLE_MANAGE_SUSPEND'),
            'ROLE_MANAGE_GROUPS'     => array('ROLE_MANAGE_GROUPS_VIEW', 'ROLE_GROUP_ADD', 'ROLE_GROUP_UPDATE', 'ROLE_GROUP_DELETE'),
            'ROLE_MANAGE_PERMISSION' => array('ROLE_MANAGE_USERS', 'ROLE_MANAGE_GROUPS'),
            'ROLE_MANAGE_SECURITY'   => array('ROLE_MANAGE_USERS', 'ROLE_MANAGE_GROUPS', 'ROLE_MANAGE_PERMISSION', 'ROLE_MANAGE_ANNOUNCEMENTS', 'ROLE_PURCHASE_REQUISITION_USERS',
                                              'ROLE_AREA_USERS', 'ROLE_CATEGORY_USERS', 'ROLE_COST_HEADER_USERS', 'ROLE_ITEM_USERS', 'ROLE_ITEM_TYPE_USERS', 'ROLE_PROJECT_USERS', 'ROLE_PROJECT_TYPE_USERS', 'ROLE_SUB_CATEGORY_USERS', 'ROLE_TERMS_AND_CONDITIONS_USERS', 'ROLE_VENDOR_USERS', 'ROLE_PURCHASE_ORDER_USERS', 'ROLE_DOCUMENT_USERS', 'ROLE_BUDGET_USERS', 'ROLE_REPORT_USERS', 'ROLE_RECEIVE_USERS')
        );
    }
}